apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres-role
      app: demo-app
  template:
    metadata:
      name: db
      labels:
        role: postgres-role
        app: demo-app
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust