apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      role: redis-role
      app: demo-app
  template:
    metadata:
      name: redis
      labels:
        role: redis-role
        app: demo-app
    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - containerPort : 6379