apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  type: NodePort
  selector:
    role: result-web
    app: demo-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008