apiVersion: v1
kind: Service
metadata:
  name: voting-service
spec:
  type: NodePort
  selector:
    role: voting-web
    app: demo-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007