apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    role: postgres-role
    app: demo-app
spec:
  containers:
   - name: postgres
     image: postgres:13
     ports:
      - containerPort: 5432
     env:
      - name: POSTGRES_HOST_AUTH_METHOD
        value: trust