apiVersion: v1
kind: Pod
metadata:
  name: result-web
  labels:
    role: result-web
    app: demo-app
spec:
  containers:
   - name: result-web-container
     image: dockersamples/examplevotingapp_result
     ports:
     - containerPort: 80
