apiVersion: v1
kind: Pod
metadata:
  name: voting-web
  labels:
    role: voting-web
    app: demo-app
spec:
  containers:
   - name: voting-web-container
     image: dockersamples/examplevotingapp_vote
     ports:
     - containerPort: 80
