apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    role: worker-role
    app: demo-app
spec:
  containers:
   - name: worker-container
     image: dockersamples/examplevotingapp_worker